name: Ragnarok wiki tests 🧪
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 8 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
